graph TD
    A[Design-Only Assessment] --Intent R1, Instruction R2, QA R3--> B[Aggregator & Downloader]
    B --> C[Generate Markdown Report]
    C --> D[Less Token Inputs, More Predictable Costs]
    
    E[Design-Only Assessment + Execution-Enabled Assessment] --Intent R1, Instruction R2, QA R3, Eval R4--> F[Aggregator & Downloader]
    F --> G[Generate Markdown Report]
    G --> H[More Token Inputs, Less Predictable Costs]
